services:
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${SSH_KEY_PATH}:/root/.ssh
            - ./logs/symfony:/var/www/symfony/var/log
            #            - ./Python-2.7.18:/tmp/python2
            - ./.data/GeoLite2-City.mmdb:/usr/local/share/GeoIP/GeoLite2-City.mmdb
            - ${SSH_SCRIPT_PATH}:/usr/local/bin/cnttnc
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
