services:
    php:
        build:
            context: php8-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        extra_hosts:
            - "${MR_BURNS_HOST}"
            - "${GITLAB_HOST}"
            - "${GITLAB_SHORT_HOST}"
            - "${SNOWBALL_HOST}"
            - "${MAGGIE_KAFKA_HOST}"
            - "${MAGGIE_KAFKA_SHORT_HOST}"
            - "${MR_BURNS_KAUFMICH_HOST}"
            - "${MR_BURNS_KAUFMICH_SHORT_HOST}"
            - "${MR_BURNS_SHORT_HOST}"
            - "${SNOWBALL_KAUFMICH_HOST}"
            - "${SNOWBALL_SHORT_HOST}"
            - "${BILD_HOST}"
            - "${TWEETY_HOST}"
            - "${TWEETY_SHORT_HOST}"
            - "${KUB3_HOST}"
            - "${KUB3_SHORT_HOST}"
            - "${PODMAN2_HOST}"
            - "${PODMAN2_SHORT_HOST}"
            - "${APIDOC_HOST}"
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${SSH_KEY_PATH}:/root/.ssh
            - ./logs/symfony:/var/www/symfony/var/log
            #            - ./Python-2.7.18:/tmp/python2
            - ./.data/GeoLite2-City.mmdb:/usr/local/share/GeoIP/GeoLite2-City.mmdb
            - ${SSH_SCRIPT_PATH}:/usr/local/bin/cnttnc
    nginx:
        build: nginx
        ports:
            - 8080:80
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
